### ISSUE TITLE
Why does this plugin trusts navigation.magneticVariation NULL or exacltly 0

### ISSUE THREAD

**Issue by mgrouch** [SignalK/signalk-derived-data#136]
In both cases they are clearly wrong

**Comment by tkurki** [comment]
Which calculations are affected? Can you provide test cases with input and expected output?

**Comment by mgrouch** [comment]
Calculation true values from magnetic are affected

**Comment by tkurki** [comment]
And the test cases?

**Comment by mgrouch** [comment]
navigation.magneticVariation is NULL or 0

makes COGT same as COGM, and other things 'true' heading not correct

**Comment by tkurki** [comment]
Zero is a perfectly valid value for magnetic variation.

**Comment by mgrouch** [comment]
When its exact 0 to many decimal points chances are it’s just unknown and some device sends it as 0.

**Comment by tkurki** [comment]
I don't think we should have a special case for exactly zero. If a system has variation as zero when it should not then the system's source of variation data needs to be fixed.

**Comment by tkurki** [comment]
I am curious: what real world magnetic variation sources produce null or exactly zero values?

**Comment by mgrouch** [comment]
Many USB GPS pucks do that.
