### ISSUE TITLE
CPA and TCPA

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-derived-data#20]
Mostly note to self: Select a range to calculate CPA and TCPA for vessels within that range, then use formulas similar to http://geomalgorithms.com/a07-_distance.html to calculate CPA and TCPA for these vessels.

**Comment by joabakk** [comment]
Further links from slack discussion:
*https://github.com/lethexa/lethexa-motionpredict
*Maybe a starting point: calculate distance, bearing and more between Latitude/Longitude points https://www.movable-type.co.uk/scripts/latlong.html

**Comment by webmasterkai** [comment]
A C++ library that contains CPA TCPA calculations https://github.com/mariokonrad/marnav
