### ISSUE TITLE
closestApproach notification path does not include vessel uuid.

### ISSUE THREAD

**Issue by panaaj** [SignalK/signalk-derived-data#34]
Traffic CPA / TCP code creates a notification to the following path:
`'notifications.navigation.closestApproach.' + mmsi`

which does not include the uuid of the vessel which I think is problematic on two fronts:
1) Clients are unable to determine the vessel the notification is for
and 
2) When the mmsi is not available it creates the following notification:
```
{
	"navigation":{
		"closestApproach":{
			"undefined":{
				"value":{
					"state":"alert",
					"method":["visual","sound"],
					"message":"Crossing vessel undefined 400 m away in 9.87  minutes",
					"timestamp":"2019-06-22T23:08:00.851Z"
				},
				"$source":"derived-data",
				"timestamp":"2019-06-22T23:08:00.852Z"
			}
		}
	}
}
```

Shouldn't the notification path be ` 'notifications.navigation.closestApproach.' + vessel`?

**Comment by sbender9** [comment]
I agree, this should have the full vessel context. PRs welcome ;)

**Comment by panaaj** [comment]
Also I noticed that the path `navigation.closestApproach` path is populated in `vessels.other-vessels-uuid` and not in `vessels.self` is this correct?
