### ISSUE TITLE
Failed to start: Callback must be a function

### ISSUE THREAD

**Issue by fabdrol** [SignalK/signalk-derived-data#37]
The derived data plugin won't start, gives this error: `Failed to start: Callback must be a function`

**Comment by fabdrol** [comment]
<img width="930" alt="screenshot" src="https://user-images.githubusercontent.com/123201/64851154-1cf63480-d617-11e9-9e11-841b6ac0fd06.png">

**Comment by tkurki** [comment]
Server & plugin versions? Have you tried with latest server?

**Comment by sbender9** [comment]
@fabdrol is this still an issue?
