### ISSUE TITLE
wind/angleTrue generated instead of wind/angleTrueGround and/or wind/angleTrueWater

### ISSUE THREAD

**Issue by edefalque** [SignalK/signalk-derived-data#47]
trueWind.js code returns environment.wind.angleTrueWater.
However my Signal K Data Browser shows environment.wind.angleTrue.
Signal K plugin seems to be outdated (plugin config shows title "Derived Data with Polars, package name @ib236/signalk-derived-data) . When installing signalk-derived-data v 1.24.3, it does not show in in the Signal K Appstore/Installed and Data Browser still shows environment.wind.angleTrue.
This might be a Signal K Node Server problem. Created also https://github.com/SignalK/signalk-server-node/issues/1006#issue-589133465

**Comment by tkurki** [comment]
You have a deprecated plugin installed and it is producing another path than this plugin.
