### ISSUE TITLE
Unknown format. at Geolib.useDecimal

### ISSUE THREAD

**Issue by Jamos1988** [SignalK/signalk-derived-data#56]
Not sure if this comes from the derived data plugin, but SignalK throws an error in the server log:

`Aug 17 12:48:43 Error: Unknown format. at Geolib.useDecimal (/home/pi/.signalk/node_modules/signalk-derived-data/node_modules/geolib/dist/geolib.js:1246:19) at Geolib.getLat (/home/pi/.signalk/node_modules/signalk-derived-data/node_modules/geolib/dist/geolib.js:148:78) at Geolib.latitude (/home/pi/.signalk/node_modules/signalk-derived-data/node_modules/geolib/dist/geolib.js:153:32) at Geolib.getDistanceSimple (/home/pi/.signalk/node_modules/signalk-derived-data/node_modules/geolib/dist/geolib.js:397:34) at calculator (/home/pi/.signalk/node_modules/signalk-derived-data/calcs/cpa_tcpa.js:209:30) at /home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1862:14 at Next.valueF (/usr/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:917:14) at Next.value (/usr/lib/node_modules/signalk-server/node_modules/baconjs/dist/Bacon.js:901:31) at spawn (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:2159:42) at Object.sink (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:2208:20) at Dispatcher.pushToSubscriptions (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1223:23) at Dispatcher.pushIt (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1245:10) at Object.inTransaction (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:430:16) at Dispatcher.push (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1214:24) at Dispatcher.handleEvent (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1267:17) at /home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:242:17 at Object.sink (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1717:18) at PropertyDispatcher.Dispatcher.pushToSubscriptions (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1223:23) at PropertyDispatcher.Dispatcher.pushIt (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1245:10) at Object.inTransaction (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:430:16) at PropertyDispatcher.Dispatcher.push (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1214:24) at PropertyDispatcher.push (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1655:38) at PropertyDispatcher._handleEvent (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:2858:21) at PropertyDispatcher.Dispatcher.handleEvent (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1265:17) at Object.sink (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:242:17) at PropertyDispatcher.Dispatcher.pushToSubscriptions (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1223:23) at PropertyDispatcher.Dispatcher.pushIt (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:1245:10) at Object.inTransaction (/home/pi/.signalk/node_modules/baconjs/dist/Bacon.js:430:16)`

I have Freeboard open with an active route enabled. SignalK server 1.32 and version 1.25 derived data plugin.

**Comment by joabakk** [comment]
Seems related to https://github.com/manuelbieh/geolib/issues/175. An upgrade of geolib should fix that
