### ISSUE TITLE
navigation.​courseGreatCircle.​nextPoint.​bearingTrue​ to APB

### ISSUE THREAD

**Issue by Jamos1988** [SignalK/signalk-derived-data#57]
Is there a way to forward this sentence to an APB sentences, in order to forward it to Pypilot?
I want to use an active route in Freeboard and push it to an autopilot, like Pypilot.
I see the sentence [-]navigation.​courseGreatCircle.​nextPoint.​bearingTrue​ (no_source) visualizes the correct heading until next waypoint, but I want to forward this value somehow.

Can this be done?

**Comment by sbender9** [comment]
@tkurki answered on Slack. Current this is not implemented.
