### ISSUE TITLE
Derived data sentences not in Data browser of SignalK

### ISSUE THREAD

**Issue by Jamos1988** [SignalK/signalk-derived-data#58]
When using Freeboard with the derived data and sk-helper plugin, activating a route generates some SignalK sentences for Course Great Circle. The data for this can be seen in an app like Instrument panel, but the Data browser of SignalK does not visualize it. The Derived data "connection" is visible, but it says "0 keys". I have no filters for self or anything, so the Data browser should depect everything.

**Comment by sbender9** [comment]
This would not have anything to do with the derived data plugin.

I see a path in the Data Browser.

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/7853683/90424527-4374e900-e08c-11ea-8c55-65d568a22878.png">
