### ISSUE TITLE
True Wind Speed option based on Speed Over Ground

### ISSUE THREAD

**Issue by scurvy-dog** [SignalK/signalk-derived-data#66]
Current True Wind speed module is based on speed through water (navigate.speedThroughWater) to calculate true wind speed. Not all vessels can generate speed through water (navigate.speedOverGround) so it would be nice to have the option to use speed over ground. Though this is not as accurate it would be a nice option.

**Comment by LeaseOnLife** [comment]
same issue here, but I found a workaround, using the Plugin "Path Mapper" and duplicate navigation.speedOverGround to navigation.speedThroughWater

**Comment by sbender9** [comment]
There's also a calculation for GWD which uses SOG.

**Comment by chris0348** [comment]
I have mixed feelings about calculating TWS via SOG. As far as I know, by common definition TWS is calculated from STW.
My suggestion would be to leave TWS as is to stick to the commonly used definition. As suggested above, a good workaround if STW is not available would be to map SOG to STW.

**Comment by sbender9** [comment]
I totally agree
