### ISSUE TITLE
Timestamp should not be included to the update

### ISSUE THREAD

**Issue by sergei** [SignalK/signalk-derived-data#82]
Based on this discussion https://github.com/SignalK/signalk-server/issues/1302 @tkurki  believes the plugin should not post the timestmap along with update.

**Comment by davidsanner** [comment]
Would this update keep derived data timestamp from updating when its source data isn't being updated?    

eg.  Seems like the timestamp for derived environment.wind.directionTrue should not be updated when  navigation.headingTrue is no longer being updated.
