### ISSUE TITLE
TypeError: invalid lat ‘NaN’

### ISSUE THREAD

**Issue by sergei** [SignalK/signalk-derived-data#84]
Getting this error if GPS is not available. Although it's not fatal the message pollutes the /var/log/syslog so it would be nice not to have it

```
TypeError: invalid lat ‘NaN’
at new LatLonSpherical (/home/pi/.signalk/node_modules/@panaaj/sk-geodesy/latlon-spherical.js:50:31)
at calculator (/home/pi/.signalk/node_modules/signalk-derived-data/calcs/courseData.js:23:11)
```

**Comment by sergei** [comment]
I presume this piece of code is supposed to take care of it:
```
      let pos = vesselPosition
        ? new LatLon(vesselPosition.latitude, vesselPosition.longitude)
        : null
```
But was is happening the vesselPosition is not undefined or null, but rather the following object:
```
{
  "longitude": null,
  "latitude": null
}
```
I guess the statement above can be replaced with:
```
      let pos = vesselPosition.latitude && vesselPosition.longitude
        ? new LatLon(vesselPosition.latitude, vesselPosition.longitude)
        : null

```
but that would be rather swiping the dirt under the rug. 
I guess the question for SignalK maintenance is if position should be allowed to have lat and lon set to NaN

**Comment by sbender9** [comment]
I don't think it's defined in the spec which is right. So that code should handle either. 

But it should be

`vesselPossition && vesselPosition.latitude && vesselPoosition.longitude`

**Comment by sergei** [comment]
Thanks, I'll do the PR then.
